---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:fluxcd/helm-operator-get-started
    path: charts/python-3.6
    ref: master
  values:
    image:
      name: test-python
      repository: test/test-python
      version: 0437ec0-202002042055
      tag: 0437ec0-202002042055
      repository: scholastic-image-hub.jfrog.io
      registry: scholastic-image-hub.jfrog.io
      pullPolicy: IfNotPresent
      secret: jfrog-image-hub
    imagePullSecrets: jfrog-image-hub
    replicaCount: 1
    appName: gitops-test
    project: test
    namespace: dev
    environment: dev
    service:
      type: ClusterIP
      port: 8080
      targetPort: 8080
